Change to selenium and xvfb service template
- Change in selenium service template
- Change in xvfb service template
- Use selenium hq version 2.39 which is compatible with firefox 26

diff --git a/templates/default/init.d/selenium.erb b/templates/default/init.d/selenium.erb
--- a/templates/default/init.d/selenium.erb
+++ b/templates/default/init.d/selenium.erb
@@ -5,12 +5,23 @@
 # chkconfig: 345 90 25
 # description: Selenium server
 
-# Source function library.
-. /etc/init.d/functions
+if [[ -f /lib/lsb/init-functions ]]; then
+  . /lib/lsb/init-functions
+elif [[ -f /etc/init.d/functions ]]; then
+  . /etc/init.d/functions
+  # Pretend to be LSB-compliant
+  function start_daemon() {
+    daemon $*
+  }
+else
+  echo "Linux LSB init function script or Redhat /etc/init.d/functions is required for this script."
+  echo "See http://refspecs.linuxfoundation.org/LSB_4.1.0/LSB-Core-generic/LSB-Core-generic/iniscrptfunc.html"
+  exit 1
+fi
 
 java="/usr/bin/java"
 selenium="<%=node[:selenium][:prog_path]%>"
-lockfile="/var/lock/subsys/selenium"
+lockfile="/var/lock/selenium"
 pidfile="/var/run/selenium.pid"
 logfile="/var/log/selenium.log"
 prog="selenium-server"
@@ -45,6 +56,9 @@ stop() {
     echo -n $"Stopping $prog: "
     killproc -p $pidfile $prog
     RETVAL=$?
+
+    [ $RETVAL -eq 0 ] && echo_success || echo_failure
+
     echo
     [ $RETVAL -eq 0 ] && rm -f $lockfile $pidfile
     return $RETVAL
diff --git a/templates/default/init.d/xvfb.erb b/templates/default/init.d/xvfb.erb
--- a/templates/default/init.d/xvfb.erb
+++ b/templates/default/init.d/xvfb.erb
@@ -5,15 +5,26 @@
 # chkconfig: - 90 30
 # description: Xvfb
 
-# Source function library.
-. /etc/init.d/functions
+if [[ -f /lib/lsb/init-functions ]]; then
+  . /lib/lsb/init-functions
+elif [[ -f /etc/init.d/functions ]]; then
+  . /etc/init.d/functions
+  # Pretend to be LSB-compliant
+  function start_daemon() {
+    daemon $*
+  }
+else
+  echo "Linux LSB init function script or Redhat /etc/init.d/functions is required for this script."
+  echo "See http://refspecs.linuxfoundation.org/LSB_4.1.0/LSB-Core-generic/LSB-Core-generic/iniscrptfunc.html"
+  exit 1
+fi
 
-lockfile="/var/lock/subsys/xvfb"
+lockfile="/var/lock/xvfb"
 pidfile="/var/run/xvfb.pid"
 logfile="/var/log/xvfb.log"
 prog="Xvfb"
 
-XVFB=/usr/bin/Xvfb
+XVFB="/usr/bin/Xvfb +extension RANDR"
 STATUS=":99 -screen 0 1024x768x8"
 
 RETVAL=0
@@ -36,6 +47,9 @@ stop() {
     echo -n $"Stopping $prog: "
     killproc -p $pidfile $prog
     RETVAL=$?
+
+    [ $RETVAL -eq 0 ] && echo_success || echo_failure
+
     echo
     [ $RETVAL -eq 0 ] && rm -f $lockfile $pidfile
     return $RETVAL
